[package]
name = "acci"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
authors = ["Michael Walloschke <michael.walloschke@axians.de>"]
description = "Enterprise-grade Rust-based system with multi-tenancy support"
license = "MIT"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }

[workspace]
members = [
    "crates/acci-core",
    #"crates/acci-api",
    #"crates/acci-auth",
    #"crates/acci-db",
    #"crates/acci-frontend",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
authors = ["Michael Walloschke <michael.walloschke@axians.de>"]
description = "Enterprise-grade Rust-based system with multi-tenancy support"
license = "MIT"
repository = "https://github.com/axians/acci"

[workspace.dependencies]
# Core
tokio = { version = "1.36", features = ["full"] }
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors"] }
hyper = "1.1"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "time", "json"] }
sea-query = "0.30"

# Authentication & Security
jsonwebtoken = "9.2"
argon2 = "0.5"
rand = "0.8"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Logging & Metrics
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
metrics = "0.21"
metrics-exporter-prometheus = "0.12"

# Error Handling
thiserror = "1.0"
anyhow = "1.0"

# Testing
tokio-test = "0.4"
pretty_assertions = "1.4"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
missing_debug_implementations = "warn"
unreachable_pub = "warn"

[workspace.lints.clippy]
enum_glob_use = "deny"
pedantic = "warn"
nursery = "warn"
unwrap_used = "warn"

[workspace.metadata]
msrv = "1.75.0"
